### ISSUE TITLE
"Main file not defined" warnings

### ISSUE THREAD

**Issue by hisenb3rg** [dshemendiuk/gulp-npm-dist#3]
I'm getting this kind of warnings after running `copy:libs` task:
```
[18:27:19] Starting 'libs'...
Main file is not defined for the module body-parser
Main file is not defined for the module cookie-parser
Main file is not defined for the module express
Main file is not defined for the module morgan
```

Is this normal behaviour and is there any way to suppress it?

**Comment by denkomanceski** [comment]
I have the same issue, and it was weird why there was noone else complaining.. maybe because its just warnings, but its bugging me I cant sleep at night :D

**Comment by dshemendiuk** [comment]
This occurs when a package doesn't have a "main" field in package.json. 
I agree that it is not important to know so I remove this warning at v1.0.0
