### ISSUE TITLE
Skips required files included in package

### ISSUE THREAD

**Issue by stokedout** [dshemendiuk/gulp-npm-dist#4]
When the package in question '[jsscrollpane@2.0.22](https://github.com/vitch/jScrollPane/tree/v2.0.22)' does not contain a 'dist' folder but does contain a 'main' file then the module ignores other files which are required that do not reside in the main folder.

For example:

Abbreviated packages.json:

    {
        ...
        "main": "script/jquery.jscrollpane.js",
        ...
    }

Abbreviated package contents:

    -> script
		-> demo.js
		-> jquery.scrollpane.js
		-> jquery.scrollpane.min.js
		-> jquery.mousewheel.js
		-> mwheelintent.js
    -> style
		-> demo.css
		-> jquery.scrollpane.css

The following code

    gulp.src(npmDist({ copyUnminified: true }), { base: './node_modules' })

Yields this result:

    -> script
		-> demo.js
		-> jquery.scrollpane.js
		-> jquery.scrollpane.min.js
		-> jquery.mousewheel.js
		-> mwheelintent.js

The problem is that it does not include the css files which are not in this folder.

I think you can't assume that if the author of a package uses a main file that the contents of its folder will include everything required.

Another example of this occurring is in the '[datatables@1.10.12 package](https://github.com/DataTables/DataTables/tree/1.10.12)'

Is it possible to make a fix?

**Comment by dshemendiuk** [comment]
Hi, @stokedout 
This change can significantly affect the work of the plugin, but most likely it is useful.
Fixed at v1.0.0.
