### ISSUE TITLE
it doesn't copy all .map files

### ISSUE THREAD

**Issue by mariodeci** [dshemendiuk/gulp-npm-dist#5]
if I want to add all .map files, I configure "exclude" attributes in this way:
 excludes: [
            '/test/**/*', '/**/Gruntfile.js', '/**/gulpfile.js', '/**/package.json', '/**/package-lock.json',
            '/**/bower.json', '/**/composer.json', '/**/yarn.lock', '/**/webpack.config.js', '/**/README*',
            '/**/LICENSE*', '/**/CHANGELOG*', '/**/*.yml', '/**/*.md', '/**/*.coffee', '/**/*.ts', '/**/*.scss', '/**/*.less'
         ]
(all the default, but without **/*.map) 
but it doesn't copy all .map files of my npm depedencies

**Comment by dshemendiuk** [comment]
Hi, @mariodeci 
I've added option `replaceDefaultExcludes`. For your case, you have to set `true`

**Comment by mariodeci** [comment]
Thanks I'll try it
