### ISSUE TITLE
Glob exclusion order is wrong

### ISSUE THREAD

**Issue by dariahervieux** [dshemendiuk/gulp-npm-dist#7]
Hi :)
First of all, thank you for your cool plugin! I appreciate using it.

I'm using it with gulp 4.0.0.

Seems like in the this version `gulp.src()` globs order is interpreted differently.
From `gulp.src()` [docs](https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpsrcglobs-options):
> A glob that begins with ! excludes matching files from the glob results up to that point. 

So according to that, you should first include patterns and then exclude.

Currently it's the opposite:
```
    // Excludes
    excludes.map(function (value) {
      packages.push('!' + mainFileDir + '/**/' + value);
    });
    // Includes
    packages.push(mainFileDir + '/**/*');
```
Would you please consider fixing it?

**Comment by dshemendiuk** [comment]
Thanks, @dariahervieux 
Fixed
