### ISSUE TITLE
Add option to specify location of node_modules and package.json

### ISSUE THREAD

**Issue by mersadk** [dshemendiuk/gulp-npm-dist#9]
In my project `node_modules` directory and `package.json` file are not in the same directory as `gulpfile.js`, they are one level up. 
As it is now, when I try to run gulp I get 
> : no such file or directory

It would be nice to have an option to specify location of `node_modules` directory and `package.json` file.

**Comment by Ylaana** [comment]
@mersadk I have created pull request #10 to address this issue.

**Comment by dshemendiuk** [comment]
Thanks to @thedutchess
Please update to latest version.
